name: CI/CD Pipeline with Docker & PM2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: MyDev
        password: 12345ser

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: MyDev/demoPro:latest

    - name: Deploy to EC2 Server
      uses: appleboy/ssh-action@v1
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull MyDev/demoPro:latest
          docker stop demoPro || true
          docker rm demoPro || true
          docker run -d --name demoPro -p 3000:3000 MyDev/demoPro:latest
          docker exec demoPro pm2 list
