name: CI/CD Pipeline with Docker Hub

on:
  push:
    branches:
      - main  # Jab bhi main branch me push hoga, auto-deploy start hoga

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -t MyDev/demoPro:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push MyDev/demoPro:latest

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker pull MyDev/demoPro:latest
            docker stop demoPro || true
            docker rm demoPro || true
            docker run -d --name demoPro -p 3000:3000 MyDev/demoPro:latest
