name: CI/CD Pipeline with Docker & PM2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/demoproject:latest

    - name: Deploy to EC2 Server
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          # Purana container stop aur remove karo
          docker stop demoproject || true
          docker rm demoproject || true
          
          # Purani unused images delete karo
          docker image prune -af
          
          # Naya image pull karo
          docker pull ${{ secrets.DOCKER_USERNAME }}/demoproject:latest
          
          # Naya container run karo
          docker run -d --name demoproject -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/demoproject:latest
